micronaut:
    application:
        name: micronautExample
    server:
        port: 8888

jpa:
    default:
        packages-to-scan:
            - 'com.smartdiscover.domain'
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true

datasources:
    default:
        url: "jdbc:h2:./devDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
        username: "sa"
        password: ""
        driverClassName: "org.h2.Driver"

